[package]
name = "poet_sys"
version = "0.1.0"
authors = ["Connor Imes <cimes@mozilla.com>"]

[dependencies]
libc = "0.1"

[dependencies.heartbeats_sys]
git = "https://github.com/connorimes/heartbeats_sys.git"
